### PR TITLE
LOGBACK-1075 and LOGBACK-1076

### PR DESCRIPTION
**Pull request by Janario**
Changes to work on modular application.
In my case Wildfly, logback as a module

More details in the issues LOGBACK-1075 and LOGBACK-1076

### CODE REVIEW

**Comment by tony19** [comment]
This looks like a duplicate of #255.

**Comment by Janario** [comment]
@tony19,
Yes it is quite related to #255 
But as I've seen none was integrated and still a problem.

In my pull request I've done changes to try as a fallback (not global) and may not affect other users once they should still work as it is already in current logback. To users that fails it will try from other CL and works if it found resources

- resources LOGBACK-1075 <property resource="my-file.properties"/>
- application appender LOGBACK-1076
- conditional with janino LOGBACK-1077

**Comment by mkurz** [comment]
Since #255 never made it in coul we give that pull request another chance?

**Comment by nafg** [comment]
Pretty please?

**Pull request closed without merging**
