### PR TITLE
[LOGBACK-1567] Upgrade to jansi 2.3.4

### PR DESCRIPTION
**Pull request by siwee**
Signed-off-by: aomsweet <aomsweet@tutanota.com>

### CODE REVIEW

**Comment by aomsweet** [comment]
@ceki 
I upgraded jansi to 2.3.4, but after Jansi 2.0, the current terminal stream cannot be wrapped (currently I have not found a way). Therefore, the test that compares the printed content will fail. Looking forward to your review and suggestions.

**Comment by aomsweet** [comment]
@ceki Hi.

I upgraded jansi to 2.3.4, but after Jansi 2.0, the current terminal stream cannot be wrapped (currently I have not found a way). Therefore, the test that compares the printed content will fail. Looking forward to your review and suggestions.

**Comment by ceki** [comment]
The new way jansi 2.x installs its streams seems quite testing unfriendly. I am reverting to version 1.18 for the moment,

**Comment by aomsweet** [comment]
OK, thanks.

**Comment by bmarwell** [comment]
Any chance we get JAnsi 2 at some point?

**Comment by ceki** [comment]
This issue has been solved in [logback 1.3.7/1.4.7 and later](https://logback.qos.ch/news.html#1.3.7).

**Pull request closed without merging**
