### PR TITLE
LOGBACK-1071: Java 8 compact3 profile compatibility

### PR DESCRIPTION
**Pull request by urechm**
LOGBACK-1071: Introduced lightweight java beans abstraction in order to get rid of dependency on java.beans package, which is not included in java 8 compact3 profile.

### CODE REVIEW

**Comment by urechm** [comment]
The tests seem to be instable, is there a way to rerun the tests?

**Comment by ceki** [comment]
I am working on fixing the two tests ( RollingCalendarTest.testCollisionFreenes and TimeBasedRollingWithArchiveRemoval_Test.checkCleanupForDailyRolloverWithInactivity_10Periods) which are currently failing. As long as the other tests pass, it's all good. Have you run the tests locally?

**Comment by urechm** [comment]
Locally the following tests failed:
TimeBasedRollingWithArchiveRemoval_Test.dailySizeBasedRolloverWithSizeCap
ReconfigureOnChangeTaskTest.fallbackToSafe_FollowedByRecovery
ReconfigureOnChangeTaskTest.fallbackToSafeWithIncludedFile_FollowedByRecovery
When I add the @Ignore annotation the build went fine.

Since the first one also failed on my previous pull request locally, but went fine on the server, I assumed it would be the same with this pull request. But maybe I really broke the latter two tests.

**Comment by ceki** [comment]
I recently fixed ReconfigureOnChangeTask.allbackToSafe* and  TimeBasedRollingWithArchiveRemoval_Test.dailySizeBasedRolloverWithSizeCap which might explain the different observations.

**Comment by urechm** [comment]
Ok, then I hope your fixes will solve the problem.

**Pull request merged**
