### PR TITLE
Custom StatusLevel for OnConsoleStatusListener

### PR DESCRIPTION
**Pull request by tillmannheigel**
Set StatusLevel for OnConsoleStatusListener in logback.xml 

`
 <statusListener class="ch.qos.logback.core.status.OnConsoleStatusListener">
     <level>(INFO|WARN|ERROR)</level>
 </statusListener>
`

[LOGBACK-1323](https://jira.qos.ch/browse/LOGBACK-1323)

### CODE REVIEW

**Comment by tillmannheigel** [comment]
I'd really like to merge this. Anything blocking here?

**Comment by romani** [comment]
@ceki , please pay attention to additional proposal in JIRA issue.
Some solution will be good to have in library, to avoid bunch of custom code in each project that use logbook extensively.

**Comment by tillmannheigel** [comment]
Doesn't seem to get attention...so I'll close it

**Comment by ceki** [comment]
PR without an associated Jira issue fall through the cracks.

**Comment by tillmannheigel** [comment]
[LOGBACK-1323](https://jira.qos.ch/browse/LOGBACK-1323) was linked. Just to understand (I actually don't need this feature anymore)...Should this have been done differently?

**Pull request closed without merging**
