### PR TITLE
Create Chinese translate

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
@ceki Hi, can you help me review Chinese translate? Thank you.

**Comment by ceki** [comment]
As I do not speak Chinese, merging the Chinese translation into the logback site is probably not a good idea. However, I'd be very happy to link to the Chinese translation hosted at another site.

**Comment by LinuxSuRen** [comment]
Ok than, it will be useful to millions of Chinese java developer, that if linked these translation document to another site.
But another site mean your site or my blog site?

**Comment by LinuxSuRen** [comment]
Or you can use google translator verify my translation. I already do some works in another project, so you can refer it.
https://github.com/jenkinsci/jenkins/pulls?q=is%3Apr+author%3ALinuxSuRen+is%3Aclosed

**Comment by ceki** [comment]
By "another site" I mean any site under **your** control.

**Comment by LinuxSuRen** [comment]
http://surenpi.com/2018/03/25/logback-document/
Can you visit this site?

**Comment by ceki** [comment]
I have just visited  http://surenpi.com/2018/03/25/logback-document/ . Do you have other pages from the manual translated?

**Comment by LinuxSuRen** [comment]
I just finish the chapter 'introduction'.

**Comment by LinuxSuRen** [comment]
Closed due to no response from the maintainers for a very long time.

**Pull request closed without merging**
