### PR TITLE
README: fix formatting of section headers

### PR DESCRIPTION
**Pull request by frankschmitt**
Add spaces between # and the section headers to ensure they are displayed correctly on Github

### CODE REVIEW

**Comment by timolehto** [comment]
lol we got sum duplicates it seems:
https://github.com/qos-ch/logback/pull/421

**Comment by timolehto** [comment]
and https://github.com/qos-ch/logback/pull/377

**Comment by timolehto** [comment]
I guess this is quite dead project. PR from over a year ago about simple README.md formatting is not getting through.. xD

**Comment by frankschmitt** [comment]
I'm somewhat disappointed by the lack of feedback from the maintainers for this pull request (and its duplicates #377 and #421. The format of README.md is still broken, and surely, one of these pull requests can be easily merged and the other ones closed as duplicates?

**Comment by frankschmitt** [comment]
This has finally been fixed with #452 - closing

**Pull request closed without merging**
