### PR TITLE
Added support for loading Tomcat Valve from classpath

### PR DESCRIPTION
**Pull request by dahankzter**
I would need something like this in our spring boot applications that we want to be independent of out-of-jar situated files.

### CODE REVIEW

**Comment by dahankzter** [comment]
I didn't see #263 from @dave-r12 

If that can be accepted then just abandon this one.

**Comment by dahankzter** [comment]
You can possibly take the tests from this pr I guess. The LogbackValve is seriously lacking in this aspect unless I am missing something.

**Comment by ceki** [comment]
@dahankztee Given this PR, would you be willing to sign a CLA [1]? Please see [2] for a justification of the CLA. Please note that by signing the CLA, you attest that your contributions are your original creations (condition 5) and that you are legally entitled (condition 4) to grant a license to QOS.ch Sarl.

In case you agree, then please send your signed CLA directly to me by email (ceki AT qos.ch) or by snail mail to

Attn: Ceki Gulcu
QOS.CH Sarl
rue Enning 3
1003 Lausanne
Switzerland.

A scanned copy on two separate pages is fine but please make sure that the images render reasonably well when printed on a laser printer. Images taken by cellphone cameras often do not render well.

[1] http://logback.qos.ch/cla.txt
[2] https://github.com/qos-ch/logback/blob/master/src/main/clas/signed-clas.txt

**Comment by dahankzter** [comment]
Sure I can sign it and rebase the PR

**Comment by dahankzter** [comment]
I had another look and it seems that it has been resolved by you @ceki .
We can just close this PR i guess but please correct me if I am wrong.

**Pull request closed without merging**
