### PR TITLE
[LOGBACK-540] Filtering out selected stack trace frames

### PR DESCRIPTION
**Pull request by nurkiewicz**
This PR adds capability of filtering selected stack frames if it's decided that they are irrelevant. You can use it by defining patterns that, if are contained within stack line, suppress displaying it:

```xml
<property name="ignored" value="
  AbstractPlainSocketImpl,
  sun.net.www.http.HttpClient,
  sun.net.www.protocol.http.HttpURLConnection.connect
"/>

<!-- and later: -->
<pattern>%d{HH:mm:ss.SSS} | %m%n%rEx{full,${ignored}}</pattern>

<!-- or directly: -->
<pattern>%d{HH:mm:ss.SSS} | %m%n%rEx{full,AbstractPlainSocketImpl,
  sun.net.www.http.HttpClient,
  sun.net.www.protocol.http.HttpURLConnection.connect}</pattern>
```

If some stack lines were ignored while showing stack trace, small indicator tells how many lines were skipped:

```
java.net.UnknownHostException: sopsdsfjdskjfskjfdskj.com
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_31] [1 skipped]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_31]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_31]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_31]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168) ~[na:1.8.0_31] [5 skipped]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104) ~[na:1.8.0_31]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998) ~[na:1.8.0_31]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512) ~[na:1.8.0_31] [1 skipped]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[na:1.8.0_31]
	at Foo.main(Foo.java:12) ~[test-classes/:na]
```

Issues is discussed in [`[LOGBACK-540]`](http://jira.qos.ch/browse/LOGBACK-540) and further discussed here: [*Filtering irrelevant stack trace lines in logs*](http://www.nurkiewicz.com/2012/03/filtering-irrelevant-stack-trace-lines.html)

### CODE REVIEW

**Comment by tony19** [comment]
Thanks for the contribution, @nurkiewicz. Please add a comment here with release notes (see rule P7 of [CONTRIBUTING.md](https://github.com/qos-ch/logback/blob/master/CONTRIBUTING.md)).

**Comment by nurkiewicz** [comment]
Thanks @tony19 for review, fixed. Release notes comment:

```html
<p>Irrelevant or internal stack trace lines can now be omitted. Pull request provided by
    Tomasz Nurkiewicz (<a href="http://jira.qos.ch/browse/LOGBACK-540">LOGBACK-540</a>).
</p>
```

**Comment by tony19** [comment]
@nurkiewicz, please also update the docs to indicate this new feature. Thanks

**Comment by nurkiewicz** [comment]
Thanks, I'm about to leave for vacation for two weeks, will do a separate PR with documentation changes after that.

**Comment by EngineerBetter** [comment]
@nurkiewicz Did you get a chance to raise the documentation PR? I had a quick look for it, but couldn't find it. I'm having difficulty getting the cool new functionality to work.

**Comment by EngineerBetter** [comment]
@nurkiewicz Ah, turns out it was a PEBKAC issue! All working splendidly now. Thanks very much, this feature is helping me mitigate a production log velocity issue.

**Comment by redron** [comment]
Hi,
I am trying to combine this feature with replace statement:
  ```%replace(%ex{full, org.springframework}){'\n', '|||'}%nopex```
 and it seems that there is no support of such an expressions yet. I wasn't able to find any workarounds so far. 
Can you please advice on it?
Thanks.

**Comment by ndjensen** [comment]
Is this going to be documented in the layouts page of the guide?

Also it doesn't seem to work well when using logback's colors for patterns.

**Pull request merged**
