### PR TITLE
LOGBACK-1250 Configure logback-access from system property

### PR DESCRIPTION
**Pull request by obourgain**
This PR adds the ability to specify the logback-access configuration file with a system property.

### CODE REVIEW

**Comment by ceki** [comment]
Hi, could you please add a Jira issue for this PR?

**Comment by obourgain** [comment]
the Jira issue is https://jira.qos.ch/browse/LOGBACK-1250

**Comment by nmaupu** [comment]
That would be indeed super useful !

**Comment by obourgain** [comment]
Hello, any update on this issue ?

**Comment by nmaupu** [comment]
L O L

**Pull request closed without merging**
