### PR TITLE
Added the feature to update mime message before sending the email

### PR DESCRIPTION
**Pull request by tetv**
Useful to extend the SMTPAppender class in order to add some Email Headers such as X-Priority, In-Reply-To, ...

### CODE REVIEW

**Comment by ceki** [comment]
Why is there a need to pass CyclicBuffer to updateMimeMsg()?

**Comment by tetv** [comment]
Because it can be useful to calculate for example the highest level of all messages and do something like:
```groovy
Level highLevel = cb.asList().stream().map(ILoggingEvent::getLevel).max(comparingInt(Level::toInt)).orElse(Level.DEBUG);
mimeMsg.setHeader("X-Priority", convertToPriorityString(highLevel));
```

**Comment by ceki** [comment]
I see. Please create a jira issue for this PR. Otherwise, it will fall through the cracks.

**Comment by tetv** [comment]
Done: LOGBACK-1284

**Pull request merged**
