### PR TITLE
Verify hostname fix

### PR DESCRIPTION
**Pull request by osigida**
PR https://github.com/qos-ch/logback/pull/305 looks stale; 
changes are cherry picked and a bit renovated

### CODE REVIEW

**Comment by ceki** [comment]
Fixed in https://github.com/qos-ch/logback/commit/626c7733c18 (1.2 branch)

**Comment by husseyd** [comment]
Thank you!

**Comment by alexsheppard11** [comment]
A minor point, can the branch `branch_1.2.x` have its poms bumped to `1.2.7` as it is still on `-SNAPSHOT`.

**Comment by ceki** [comment]
Sorry about that. Updated to 1.2.8-SNAPSHOT.

**Pull request closed without merging**
