### PR TITLE
Report exceptions from ArchiveRemover

### PR DESCRIPTION
**Pull request by findepi**

### CODE REVIEW

**Comment by ceki** [comment]
@findepi Looking at your change for about 2 seconds, it seems that it has nothing to do with exceptions but waiting for the previous task to finish. What am I missing?

**Comment by findepi** [comment]
@ceki thanks for your feedback. Yes, this isn't clear in the diff.
My hope is that `addError` here: 
https://github.com/qos-ch/logback/blob/8607f601e0ef8c6fd9b41f3e4ba9bff8dc0b2548/logback-core/src/main/java/ch/qos/logback/core/rolling/TimeBasedRollingPolicy.java#L140-L141
does some kind of reporting.

If it doesn't, what should I do to report problem?
I am new to the codebase, and I don't know how you handle logging [inside logging framework].

**Comment by findepi** [comment]
@ceki am I wrong?

**Comment by findepi** [comment]
@ceki did I convince you?

**Comment by findepi** [comment]
@ceki should I close the PR?

**Comment by ceki** [comment]
Please create a Jira issue linking to this PR. I'll look at it at a later time.

**Comment by findepi** [comment]
@ceki i would appreciate if you can create it (https://jira.qos.ch/projects/LOGBACK).
i don't have an account there.

**Comment by ceki** [comment]
@findepi  Sorry but I am probably as busy as you.

**Pull request closed without merging**
