### PR TITLE
LOGBACK-1175 LOGBACK-1217 improve FileNamePattern regex

### PR DESCRIPTION
**Pull request by gracew**
related: https://github.com/qos-ch/logback/pull/322, https://github.com/qos-ch/logback/pull/338

### CODE REVIEW

**Comment by gracew** [comment]
@ceki , could you take a look at this? it closes two (!) jira tickets.

**Comment by gracew** [comment]
ping, it would be really great to get this into logback 1.3. I'm happy to make an addition to https://github.com/qos-ch/logback/blob/master/logback-site/src/site/pages/news.html if that would help with getting this merged.

**Comment by jnewman2501** [comment]
Ping - this would be awesome!

**Comment by samfrown** [comment]
Hi! This is very usefull fix for us too.

**Comment by ndhar-1** [comment]
So this commit is not part of 1.2.3 release ? Which release then ?

**Comment by ceki** [comment]
fixed in 1.3.0-alpha1

**Pull request closed without merging**
